### ISSUE TITLE
fix usersidebar

### ISSUE THREAD

**Issue by kartikey-mittal** [kartikey-mittal/karotask#5]
fix usersidebar

last area issue

**Comment by jain-lakshay** [comment]
issue solved
![Uploading Screenshot 2024-12-03 at 8.00.16 PM.png…]()

**Comment by jain-lakshay** [comment]
issue solved 
<img width="1440" alt="Screenshot 2024-12-03 at 8 00 16 PM" src="https://github.com/user-attachments/assets/6a2aa9c6-c7bf-4b6e-a1fd-d38b5131e0e1">
